version: '3'
services:
  bert-cola-news:
    image: "p0seid0n/tf_serving_bert_cola_news:1563578991_v1"
    environment:
      - MODEL_NAME=bert
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "800M"
        reservations:
          cpus: "0.25"
          memory: "100M"
    ports:
      - "8500:8500"
      - "8501:8501"
    labels:
      kompose.service.type: LoadBalancer
  bert-client:
    image: "p0seid0n/bert_cola_news_client"
    ports:
      - "5000:5000"
    depends_on:
      - bert-cola-news
    labels:
      kompose.service.type: LoadBalancer
